### PR TITLE
introducing a engines bound in package.json

### PR DESCRIPTION
**Pull request by CarstenKoenig**
using **optional catch binding** depends on node version > 10.3.0 (see https://node.green/#ES2019-misc-optional-catch-binding-basic)

the package will no longer build on earlier nodes - see the comments on the introducing commit (https://github.com/shinnn/install-purescript-cli/commit/779a4e7ec89576d3f2004a5e48fb8fc587d09bb9)

### CODE REVIEW

**Comment by CarstenKoenig** [comment]
I have no clue why the travis build is having permission troubles.

Please let me know if you see the problem.

**Comment by shinnn** [comment]
Ignore the test failure. I'll fix it in the future by myself.

**Comment by shinnn** [comment]
Thanks for the suggestion, but [the main consumer of this package](https://github.com/purescript-contrib/node-purescript) already has [`engine` field](https://github.com/purescript-contrib/node-purescript/blob/v0.13.0/package.json#L8-L11) and I think that's enough. No humans would install this package directly in favor of `purescript`.

**Comment by CarstenKoenig** [comment]
alright - interestingly I did not get a warning when I tried to install purescript via npm ... well thanks for your time and helping me out - learned a lot about node today

**Comment by shinnn** [comment]
> I did not get a warning when I tried to install purescript via npm

It seems to be a known bug of npm CLI. https://npm.community/t/engines-and-engines-strict-ignored/4792/4

Since the topic is automatically closed, you can help a lot of npm users including me if you open a new topic about the same problem.

**Pull request closed without merging**
